# Generated by Django 5.1.4 on 2024-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0002_rename_indicador1_indicador_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarestudiante',
            name='periodo_academico',
            field=models.CharField(default=-1, max_length=100),
        ),
    ]
